apiVersion: apps/v1
kind: Deployment

metadata:
  name: secure-node-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: secure-node-app

  template:
    metadata:
      labels:
        app: secure-node-app

    spec:
      containers:
      - name: secure-node-app

        image: ismail2813/secure-devsecops-app:latest

        ports:
        - containerPort: 3000